[package]
name = "rust_stdf_helper"
version = "0.2.4"
edition = "2021"

[profile.release]
lto = "fat"
codegen-units = 1

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rust_stdf_helper"
# crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.17.1", features = ["extension-module"] }
rust-stdf = { version = "0.3.1", features = [ "zipfile", "serialize" ] }
rusqlite = { version = "0.28.0", features = ["bundled"]}
# ndarray = { version = "0.15.6", features = ["rayon"] }
zip = { version = "0.6.3", default-features = false, features = ["deflate", "bzip2", "zstd"] }
# numpy = "0.17.2"
chrono = "0.4.22"
hex = "0.4.3"
lazy_static = "1.4.0"
serde_json = "1.0.87"
flate2 = { version = "1.0.24"}
rust_xlsxwriter = "0.12.1"
